[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "experiment_utils"
version = "0.0.5-beta"
authors = [
  { name="Aaron Mishkin", email="amishkin@cs.stanford.edu" },
]
description="A lightweight package for managing optimization and machine learning experiments.",
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.21.3",
    "torch>=1.10.0",
    "matplotlib",
    "typing_extensions",
]

[tool.setuptools.package-data]
scnn = ["py.typed"]

[project.urls]
"Homepage" = "https://github.com/aaronpmishkin/experiment_utils"
"Bug Tracker" = "https://github.com/aaronpmishkin/experiment_utils/issues"

